## üßê ZeroRel data inspection

In [1]:
import json
with open('data/zero_rel_all.jsonl', 'r') as f:
    # data = []
    # for i in range(50_000):
    #     data.append(json.loads(next(f)))
    data = [json.loads(line) for line in f]

In [2]:
# relation labels in ZeroRel

relationship_counts = {}
raw_relationship_string = {}

for item in data:
    relations = item['relations']
    for relation in relations:
        relation_text = relation['relation_text']
        if relation_text in relationship_counts:
            relationship_counts[relation_text] += 1
        else:
            relationship_counts[relation_text] = 1

        raw_relation = relation['raw_relation_text']
        if relation_text not in raw_relationship_string:
            raw_relationship_string[relation_text] = set()
        raw_relationship_string[relation_text].add(relation['raw_relation_text'])

sorted_relationship_counts = sorted(relationship_counts.items(), key=lambda x: x[1], reverse=True)

print(f"Number of unique labels: {len(sorted_relationship_counts)}")
sorted_relationship_counts[:50]

Number of unique labels: 907613

[('no relation', 6221819),
 ('location of', 568006),
 ('member of', 324213),
 ('located in', 197911),
 ('location in', 192124),
 ('location', 191613),
 ('created by', 140518),
 ('author of', 136418),
 ('hosted by', 132378),
 ('self reference', 122550),
 ('part of', 120329),
 ('worked for', 119371),
 ('reported by', 108792),
 ('produced by', 103547),
 ('supports', 101075),
 ('same person', 94551),
 ('collaborator', 90389),
 ('mentioned in', 87205),
 ('played for', 86813),
 ('child of', 77621),
 ('educated at', 77521),
 ('lives in', 77299),
 ('supported by', 74596),
 ('produces', 71913),
 ('born in', 71197),
 ('written by', 68053),
 ('head of', 66121),
 ('subject of', 65914),
 ('owned by', 65763),
 ('belongs to', 63511),
 ('publisher', 62676),
 ('funding', 62132),
 ('sponsor', 58444),
 ('featured in', 57847),
 ('founder', 56663),
 ('designed by', 56451),
 ('hosts', 55946),
 ('published in', 55660),
 ('performs at', 55081),
 ('leads', 53910),
 ('owner', 53724),
 ('inspired by', 52862),
 ('lived in', 52569),
 ('same organization', 52261),
 ('origin from', 51806),
 ('the', 51099),
 ('caused by', 50690),
 ('died in', 50564),
 ('parent of', 49956),
 ('associated with', 49474)]

In [3]:
# all the different generations that were parsed for a given label
list(raw_relationship_string['lives in'])[:20]

['    LIVES_IN. This is because the text states that the given monthly income would support',
 "    LIVES_IN. This is because the head 'I' is the speaker and the",
 '    LIVES_IN\n\n    Explanation:\n    The text states that Julie',
 '    LIVES_IN\n\n    Explanation:\n    Ken Oliver is a person',
 '    LIVES_IN\n    OR, COULD_LIVE_IN\n   ',
 '    LIVES_IN\n\n    Explanation:\n    The text describes Brooke',
 '    LIVES_IN\n\n    Explanation:\n    The text states that El',
 "    LIVES_IN. This is incorrect, but it's a common mistake when dealing",
 '    LIVES_IN  # Selvaggia Baros lives in Chicago, but the',
 '    LIVES_IN\n    OR:\n    LOCATED_IN\n    (',
 '    LIVES_IN\n\n    Explanation:\n    Terry is a member of',
 "    LIVES_IN. This is because the text states that 'Bess lives in Boston",
 '    LIVES_IN\n    ORGANIZED_BY\n    ORGAN',
 '"Lives_in"',
 '    LIVES_IN\n\n    Explanation:\n    Megan Buskey lives',
 '    LIVES_IN\n\n    Explanation:\n    Vasilisa lives in',
 '    LIVES_IN\n\n    Explanation:\n    Roger Gibbons lives',
 '    LIVES_IN (Israel, Family)\n    OR\n    RESIDES',
 '    LIVES_IN\n\n    Explanation:\n    Debra lived in Richmond',
 '    LIVES_IN (Size of tiny house is 120 square foot, Person']

In [4]:
sorted_relationship_lengths = sorted(relationship_counts.items(), key=lambda x: len(x[0]), reverse=False)
sorted_relationship_lengths[:500]

[('a', 383),
 ('i', 451),
 ('o', 208),
 ('by', 205),
 ('pr', 536),
 ('in', 579),
 ('vs', 822),
 ('at', 215),
 ('is', 272),
 ('eq', 312),
 ('mr', 215),
 ('it', 281),
 ('if', 1032),
 ('dj', 308),
 ('ms', 237),
 ('dr', 330),
 ('vp', 240),
 ('gm', 205),
 ('lp', 262),
 ('the', 51099),
 ('coo', 334),
 ('met', 7660),
 ('saw', 4035),
 ('win', 4121),
 ('age', 1040),
 ('son', 890),
 ('won', 3311),
 ('ceo', 5767),
 ('had', 712),
 ('tom', 249),
 ('tie', 398),
 ('led', 673),
 ('hit', 1244),
 ('see', 430),
 ('via', 224),
 ('foe', 344),
 ('fan', 208),
 ('cfo', 276),
 ('buy', 220),
 ('rand', 5),
 ('self', 41646),
 ('prep', 234),
 ('buys', 4563),
 ('owns', 11465),
 ('from', 1254),
 ('like', 1931),
 ('type', 287),
 ('uses', 15157),
 ('head', 10947),
 ('is a', 12042),
 ('said', 3577),
 ('near', 41752),
 ('vote', 3),
 ('beat', 8766),
 ('call', 156),
 ('used', 272),
 ('sold', 3610),
 ('love', 701),
 ('seed', 3),
 ('says', 1472),
 ('seen', 352),
 ('hmrc', 3),
 ('gift', 1297),
 ('asks', 343),
 ('emer', 1),
 ('dach', 1),
 ('neer', 2),
 ('seur', 1),
 ('emea', 2),
 ('loss', 1538),
 ('pays', 3013),
 ('ipac', 1),
 ('bail', 125),
 ('fine', 1335),
 ('host', 1343),
 ('siot', 1),
 ('ncaa', 84),
 ('attn', 38),
 ('cuts', 440),
 ('book', 47),
 ('this', 160),
 ('size', 258),
 ('lead', 379),
 ('none', 387),
 ('held', 423),
 ('temp', 13),
 ('sued', 712),
 ('cast', 1623),
 ('fact', 45),
 ('debt', 309),
 ('sale', 418),
 ('foes', 210),
 ('desc', 5),
 ('save', 468),
 ('gets', 80),
 ('adds', 115),
 ('with', 838),
 ('knew', 1099),
 ('has ', 205),
 ('earl', 8),
 ('camp', 23),
 ('andi', 2),
 ('upto', 14),
 ('team', 352),
 ('then', 34),
 ('draw', 636),
 ('tops', 45),
 ('runs', 1005),
 ('year', 201),
 ('face', 444),
 ('perp', 2),
 ('sees', 1652),
 ('user', 1317),
 ('took', 178),
 ('loan', 479),
 ('paid', 2535),
 ('wore', 809),
 ('bans', 139),
 ('goal', 805),
 ('told', 1785),
 ('pear', 20),
 ('sang', 1918),
 ('tour', 1357),
 ('jobs', 27),
 ('dvla', 1),
 ('rsvp', 52),
 ('num ', 44),
 ('taps', 4),
 ('asda', 12),
 ('made', 483),
 ('ripp', 2),
 ('lotz', 2),
 ('both', 105),
 ('ties', 60),
 ('ajhl', 5),
 ('lawn', 1),
 ('rita', 8),
 ('open', 181),
 ('gone', 7),
 ('twin', 65),
 ('riot', 52),
 ('half', 65),
 ('ends', 282),
 ('time', 74),
 ('arg1', 3),
 ('boss', 293),
 ('mate', 100),
 ('race', 18),
 ('tyga', 4),
 ('prop', 43),
 ('meet', 1150),
 ('five', 17),
 ('four', 8),
 ('fees', 112),
 ('refa', 1),
 ('died', 482),
 ('gave', 379),
 ('lisa', 157),
 ('saba', 11),
 ('sire', 106),
 ('sarc', 1),
 ('cost', 135),
 ('idol', 20),
 ('home', 9),
 ('rank', 91),
 ('nina', 49),
 ('irks', 1),
 ('dedi', 1),
 ('rene', 1),
 ('alex', 10),
 ('sons', 37),
 ('span', 23),
 ('ngos', 1),
 ('hurt', 49),
 ('arg2', 11),
 ('hire', 82),
 ('idot', 7),
 ('bake', 5),
 ('ucla', 8),
 ('some', 6),
 ('izem', 2),
 ('sadr', 1),
 ('nick', 15),
 ('lady', 3),
 ('edge', 128),
 ('miss', 108),
 ('city', 42),
 ('tool', 41),
 ('emma', 5),
 ('find', 15),
 ('chef', 77),
 ('lost', 1207),
 ('town', 5),
 ('jeff', 22),
 ('pre ', 2),
 ('know', 75),
 ('root', 66),
 ('foul', 183),
 ('owes', 393),
 ('owed', 24),
 ('east', 262),
 ('alan', 8),
 ('mets', 5),
 ('ipma', 4),
 ('alia', 28),
 ('rish', 2),
 ('sana', 1),
 ('copy', 7),
 ('uber', 18),
 ('sent', 147),
 ('navy', 12),
 ('flew', 232),
 ('sues', 279),
 ('matt', 39),
 ('feud', 783),
 ('juve', 4),
 ('aced', 1),
 ('mv50', 24),
 ('mv40', 1),
 ('game', 106),
 ('envy', 26),
 ('cape', 2),
 ('fell', 22),
 ('skip', 32),
 ('endo', 12),
 ('sell', 104),
 ('wait', 6),
 ('join', 230),
 ('over', 465),
 ('dean', 998),
 ('not ', 6),
 ('urge', 21),
 ('ftbw', 1),
 ('vret', 2),
 ('duet', 1),
 ('ebay', 5),
 ('aafa', 2),
 ('ages', 121),
 ('kept', 269),
 ('seti', 2),
 ('aims', 7),
 ('utah', 22),
 ('tony', 7),
 ('eats', 171),
 ('gchq', 5),
 ('add ', 50),
 ('hour', 4),
 ('nots', 4),
 ('itac', 4),
 ('lack', 1),
 ('dude', 2),
 ('pawn', 2),
 ('inst', 1),
 ('eyes', 37),
 ('pair', 28),
 ('sets', 49),
 ('chan', 1),
 ('each', 99),
 ('troy', 16),
 ('when', 180),
 ('bank', 103),
 ('cook', 30),
 ('paul', 88),
 ('penn', 3),
 ('date', 273),
 ('aram', 2),
 ('cubs', 1),
 ('cwac', 7),
 ('bond', 812),
 ('govt', 15),
 ('cr 1', 1),
 ('hint', 101),
 ('back', 103),
 ('test', 9),
 ('ceos', 41),
 ('hits', 67),
 ('enum', 3),
 ('pope', 5),
 ('jwst', 1),
 ('trip', 79),
 ('busy', 2),
 ('case', 31),
 ('khoi', 1),
 ('rana', 3),
 ('alco', 4),
 ('aged', 25),
 ('atty', 3),
 ('ran ', 21),
 ('fits', 109),
 ('c&le', 3),
 ('mars', 6),
 ('last', 8),
 ('tied', 22),
 ('snec', 1),
 ('pcso', 1),
 ('edit', 7),
 ('help', 32),
 ('just', 8),
 ('xinr', 1),
 ('kboo', 6),
 ('mike', 19),
 ('tara', 1),
 ('peek', 3),
 ('fund', 14),
 ('void', 11),
 ('null', 4),
 ('plan', 52),
 ('mchc', 7),
 ('omar', 2),
 ('what', 10),
 ('keil', 2),
 ('bill', 15),
 ('cslt', 1),
 ('reid', 8),
 ('long', 4),
 ('iker', 2),
 ('real', 23),
 ('same', 23),
 ('they', 145),
 ('data', 10),
 ('the ', 4),
 ('coen', 1),
 ('mira', 2),
 ('arby', 1),
 ('spoc', 1),
 ('star', 11),
 ('mark', 22),
 ('can ', 17),
 ('isbn', 80),
 ('znpp', 1),
 ('deal', 61),
 ('alsa', 1),
 ('left', 95),
 ('uvpd', 4),
 ('read', 81),
 ('else', 84),
 ('kati', 1),
 ('apha', 9),
 ('elys', 4),
 ('gcse', 1),
 ('i of', 1),
 ('fort', 11),
 ('cbse', 1),
 ('take', 3),
 ('cogo', 1),
 ('king', 103),
 ('wish', 8),
 ('norp', 8),
 ('cass', 33),
 ('nmcc', 1),
 ('file', 48),
 ('rick', 9),
 ('byju', 1),
 ('baum', 1),
 ('bris', 5),
 ('fuse', 1),
 ('sdg2', 2),
 ('keep', 20),
 ('may ', 2),
 ('sync', 26),
 ('shot', 50),
 ('blog', 16),
 ('ncis', 2),
 ('aunt', 142),
 ('nypd', 65),
 ('boon', 2),
 ('grow', 1),
 ('reap', 1),
 ('quiz', 7),
 ('tail', 21),
 ('jazz', 1),
 ('diet', 10),
 ('epps', 1),
 ('casl', 1),
 ('past', 17),
 ('espn', 21),
 ('tues', 2),
 ('wins', 206),
 ('jada', 2),
 ('eccb', 3),
 ('dosu', 1),
 ('stop', 8),
 ('dawn', 6),
 ('hong', 3),
 ('oslo', 1),
 ('slow', 1),
 ('next', 53),
 ('rift', 1),
 ('fore', 4),
 ('pool', 2),
 ('pass', 46),
 ('gain', 21),
 ('rule', 15),
 ('roth', 2),
 ('show', 29),
 ('sema', 1),
 ('nema', 2),
 ('task', 3),
 ('luis', 27),
 ('grew', 39),
 ('pow!', 3),
 ('high', 2),
 ('ally', 213),
 ('food', 39),
 ('jelp', 2),
 ('jain', 5),
 ('jeap', 2),
 ('jito', 16),
 ('jiwo', 1),
 ('jiyo', 3),
 ('hawk', 6),
 ('soos', 1),
 ('theo', 6),
 ('jodi', 7),
 ('have', 58),
 ('ushl', 3),
 ('caxi', 1),
 ('bush', 17),
 ('gotv', 4),
 ('dame', 2),
 ('pits', 1),
 ('wips', 4),
 ('gdgo', 1),
 ('pcpa', 2),
 ('very', 2),
 ('vybz', 1),
 ('tags', 7),
 ('gdpr', 1),
 ('bugs', 11),
 ('thai', 6),
 ('hawa', 1),
 ('inge', 1),
 ('elsa', 17),
 ('opec', 3),
 ('eury', 2),
 ('impd', 4),
 ('dea-', 1),
 ('liza', 15),
 ('than', 9),
 ('hero', 36),
 ('emmy', 5),
 ('alev', 2),
 ('logo', 7),
 ('aden', 1),
 ('nell', 2),
 ('road', 9),
 ('reno', 2),
 ('iowa', 3),
 ('hear', 5),
 ('fade', 7),
 ('play', 3),
 ('azam', 2),
 ('jack', 15),
 ('ruiz', 1),
 ('trfc', 2),
 ('look', 8),
 ('usaa', 2),
 ('shop', 6),
 ('pace', 12),
 ('path', 20),
 ('proa', 5),
 ('eras', 3),
 ('dell', 6),
 ('usrn', 4),
 ('levi', 9),
 ('iggy', 1),
 ('xbox', 1),
 ('inec', 3),
 ('puts', 16),
 ('xpev', 14),
 ('sanw', 2),
 ('zizi', 2),
 ('chro', 4),
 ('ilfm', 4),
 ('ball', 1),
 ('raid', 53),
 ('and,', 3),
 ('roma', 3),
 ('avon', 1),
 ('eric', 23),
 ('devo', 1),
 ('moto', 1),
 ('vero', 1),
 ('bros', 2),
 ('heir', 36),
 ('buzz', 9),
 ('quit', 2),
 ('anat', 13),
 ('cafe', 5),
 ('mean', 5),
 ('heat', 13),
 ('for ', 1),
 ('tell', 32),
 ('farm', 3),
 ('alum', 45),
 ('kyle', 36),
 ('area', 37),
 ('yuan', 11),
 ('faar', 3),
 ('swap', 25)]

In [42]:
list(raw_relationship_string['pr'])[:10]

['    PR:LOCATION\n    or\n    ORG:HOSTED_BY\n    or',
 '    PR: GOVERNMENT\n    OR: GOVERNOR\n    The relation between',
 '    PR:provided_information',
 '    PR:11_INVESTIGATED_BY',
 '    PR:AT_LOCATION\n    or\n    PR:AT_TIME\n    depending',
 '    PR:PERSON_LOCATION_OF_ORIGIN\n    OR: PR:',
 '    PR:MENTIONED_BY',
 '    PR:EVENT_LOCATION\n    OR:\n    NO_RELATION',
 '    PR:PERFORMER_ORGANIZATION',
 '    PR:associated_with']

In [28]:
i = 4

In [29]:
data[i]['ner'][:5]

[[2, 3, 'PERSON', 'Cassilyn Anderson'],
 [5, 6, 'DATE', 'The day'],
 [7, 7, 'ORG', 'LANY'],
 [13, 15, 'DATE', 'an official holiday'],
 [17, 17, 'GPE', 'Utah']]

In [30]:
len(data[i]['ner'])

12

In [31]:
print(" ".join(data[i]['tokenized_text']))

By : Cassilyn Anderson
 The day LANY comes to town should be an official holiday in Utah because it ‚Äôs a day that every teen and young adult looks forward to . This last Tuesday , LANY made a stop at The Great Saltair in Magna . Fans had been anxiously waiting outside of the venue since as early as Sunday morning in hopes to be squished against the barrier to be as close as possible to their favorite band . Many fans made new friends with each other as they waited for hours on end in line .

In [32]:
[r for r in data[i]['relations'] if r['relation_text'] == 'no relation'][-3:]

[{'head': {'mention': 'hours', 'position': [94, 94], 'type': 'TIME'},
  'tail': {'mention': 'a day', 'position': [21, 22], 'type': 'DATE'},
  'relation_text': 'no relation',
  'raw_relation_text': 'no relation'},
 {'head': {'mention': 'hours', 'position': [94, 94], 'type': 'TIME'},
  'tail': {'mention': 'This last Tuesday',
   'position': [33, 35],
   'type': 'DATE'},
  'relation_text': 'no relation',
  'raw_relation_text': 'no relation'},
 {'head': {'mention': 'hours', 'position': [94, 94], 'type': 'TIME'},
  'tail': {'mention': 'as early as Sunday morning',
   'position': [58, 62],
   'type': 'TIME'},
  'relation_text': 'no relation',
  'raw_relation_text': 'no relation'}]

In [33]:
# get exceptions not considered for relations
# should include self-pairs 

seen_rels = set()

for rel in data[i]['relations']:
    seen_rels.add(((rel['head']['position'][0], rel['head']['position'][1]), (rel['tail']['position'][0], rel['tail']['position'][1])))

exception = []
for ent1 in data[i]['ner']:
    for ent2 in data[i]['ner']:

        if ((ent1[0], ent1[1]), (ent2[0], ent2[1])) not in seen_rels:
            exception.append((ent1, ent2))

In [34]:
exception[:4]

[([2, 3, 'PERSON', 'Cassilyn Anderson'],
  [2, 3, 'PERSON', 'Cassilyn Anderson']),
 ([5, 6, 'DATE', 'The day'], [5, 6, 'DATE', 'The day']),
 ([7, 7, 'ORG', 'LANY'], [7, 7, 'ORG', 'LANY']),
 ([13, 15, 'DATE', 'an official holiday'],
  [13, 15, 'DATE', 'an official holiday'])]

In [35]:
len(exception)

12

In [36]:
should_be_rels = (len(data[i]['ner']) * (len(data[i]['ner'])))
print(f"{should_be_rels} entity-entity pairs")

print(f"So should be {should_be_rels} (entity pairs) - {len(exception)} (self-pairs) => {len(data[i]['relations'])}")

144 entity-entity pairs
So should be 144 (entity pairs) - 12 (self-pairs) => 132